routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/kontak', 'Web\User\KontakController');
Route::resource('/laporan', 'Web\User\LaporanController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');
Route::get('/gallery', 'Web\User\BerandaController@gallery');
Route::get('/video', 'Web\User\BerandaController@video');
Route::get('download/katalog', 'Web\User\BerandaController@download');
Route::get('/hubungi', 'Web\User\BerandaController@hubungi');

Auth::routes(['register' => false]);

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/prinsip', 'Web\Admin\PrinsipController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/photo', 'Web\Admin\GalleryController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/progres', 'Web\Admin\ProgresController');
Route::resource('/admin/testimoni', 'Web\Admin\TestimoniController');
Route::resource('/admin/pertanyaan', 'Web\Admin\PertanyaanController');
Route::resource('/admin/tim', 'Web\Admin\TimController');
Route::resource('/admin/file', 'Web\Admin\FileController');
Route::get('/admin/cetak/pesan/print/{id}', 'Web\Admin\PesanController@pesan');
Route::get('/admin/cetak/pesan-semua/print', 'Web\Admin\PesanController@pesansemua');

app/Prinsip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prinsip extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/PrinsipController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Gambar;
use App\History;
use App\Http\Controllers\Controller;
use App\Prinsip;
use Illuminate\Http\Request;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PrinsipController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $gambar = Gambar::all();
        $data = Prinsip::all();
        return view('admin.prinsip.beranda', compact('data','gambar'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function edit(Prinsip $prinsip)
    {
        $gambar = Gambar::all();
        return view('admin.prinsip.edit', compact('prinsip','gambar'));
    }

    public function update(Request $request, $id)
    {
        $prinsip = Prinsip::findOrFail($id);

        if ($request->hasFile('photo')) {
            $this->deletePhoto($prinsip->photo);
            $data['photo'] = $this->savePhoto($request->file('photo'));
        }

        $prinsip->update($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Gambar " . $prinsip->judul . " berhasil diubah ";
        History::create($histori);

        $notification = array(
            'message' => 'Gambar "' . $prinsip->judul . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('prinsip.index')->with($notification);
    }

    public function destroy($id)
    {
        //
    }

    protected function savePhoto(UploadedFile $photo)
    {
        $fileName = Str::random(10) . '.' . $photo->guessClientExtension();
        $destinationPath = 'itlabil/images/prinsip';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = 'itlabil/images/prinsip/' . $filename;
        return File::delete($path);
    }
}

resources/views/admin/prinsip/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Prinsip
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Prinsip</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Photo</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($data as $item)
                            <tr>
                                <td>{{ $item->judul }}</td>
                                <td><img src="{{asset('itlabil/images/prinsip/'.$item->photo) }}" class="img-thumbnail" width="300px" alt=""></td>
                                <td align="center">
                                    <a href="{{ route('prinsip.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/prinsip/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Data Prinsip
    </h1>
  </section><br><br>

  <div class="row">

    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Data Prinsip</h3>
        </div>
        <form action="{{ route('prinsip.update',$prinsip->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PATCH')
          <div class="box-body">
            <div class="form-group">
              <label for="{{$prinsip->judul}}" class="col-sm-4 control-label">{{$prinsip->judul}}</label>

              <div class="col-sm-8">
                <input type="file" name="photo" id="cat_image">
              </div>
            </div>
          </div>
          <div class="box-footer">
            <a href="{{url('admin/prinsip')}}" class="btn btn-default">Kembali</a>
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>

    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Sebelumnya</h3>
        </div>
        <div class="box-body">
          <img src="{{asset('itlabil/images/prinsip/'.$prinsip->photo) }}" class="img-thumbnail" width="300px" alt="">
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Preview</h3>
        </div>
        <div class="box-body">
          <img src="#" id="category-img-tag" class="img-thumbnail" width="300px" />
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection