routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/kontak', 'Web\User\KontakController');
Route::resource('/laporan', 'Web\User\LaporanController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');
Route::get('/gallery', 'Web\User\BerandaController@gallery');
Route::get('/video', 'Web\User\BerandaController@video');
Route::get('download/katalog', 'Web\User\BerandaController@download');
Route::get('/hubungi', 'Web\User\BerandaController@hubungi');

Auth::routes(['register' => false]);

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/prinsip', 'Web\Admin\PrinsipController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/photo', 'Web\Admin\GalleryController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/progres', 'Web\Admin\ProgresController');
Route::resource('/admin/testimoni', 'Web\Admin\TestimoniController');
Route::resource('/admin/pertanyaan', 'Web\Admin\PertanyaanController');
Route::resource('/admin/tim', 'Web\Admin\TimController');
Route::resource('/admin/file', 'Web\Admin\FileController');
Route::get('/admin/cetak/pesan/print/{id}', 'Web\Admin\PesanController@pesan');
Route::get('/admin/cetak/pesan-semua/print', 'Web\Admin\PesanController@pesansemua');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $guarded = [];

    public function album()
    {
        return $this->belongsTo('App\Album', 'album_id');
    }
}

resources/views/admin/photo/beranda.blade.php
@extends('layouts.admin')

@section('content')

<section class="content-header">
  <h1>
    Gallery
  </h1>
</section>

<section class="content">

  <div class="row">

    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data Progres</h3>
        </div>
        <form action="{{ route('photo.store') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="box-body">

            <div class="form-group">
              <label for="photo" class="col-sm-2 control-label">Photo</label>

              <div class="col-sm-8">
                <input type="file" name="photo" id="cat_image">
              </div>
            </div>
          </div>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Preview</h3>
        </div>
        <div class="box-body">
          <img src="#" id="category-img-tag" class="img-thumbnail" width="300px" />
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      @foreach($data as $item)
      <div class="col-md-3" style="margin-bottom: 20px;">
        <img src="{{asset('itlabil/images/photo/')}}/{{$item->photo}}" alt="{{ $item->photo }}" class="img-thumbnail">
        <br><br>
        <div class="col-md-12" align="center">
          <form action="{{ route('photo.destroy',$item->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Hapus</button>
          </form>
        </div>
      </div>
      @endforeach
    </div>

    <div class="col-md-12" align="center">
      {{ $data->links() }}
    </div>
  </div>

</section>
@endsection