routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/kontak', 'Web\User\KontakController');
Route::resource('/laporan', 'Web\User\LaporanController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');
Route::get('/gallery', 'Web\User\BerandaController@gallery');
Route::get('/video', 'Web\User\BerandaController@video');
Route::get('download/katalog', 'Web\User\BerandaController@download');
Route::get('/hubungi', 'Web\User\BerandaController@hubungi');

Auth::routes(['register' => false]);

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/prinsip', 'Web\Admin\PrinsipController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/photo', 'Web\Admin\GalleryController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/progres', 'Web\Admin\ProgresController');
Route::resource('/admin/testimoni', 'Web\Admin\TestimoniController');
Route::resource('/admin/pertanyaan', 'Web\Admin\PertanyaanController');
Route::resource('/admin/tim', 'Web\Admin\TimController');
Route::resource('/admin/file', 'Web\Admin\FileController');
Route::get('/admin/cetak/pesan/print/{id}', 'Web\Admin\PesanController@pesan');
Route::get('/admin/cetak/pesan-semua/print', 'Web\Admin\PesanController@pesansemua');

app/Http/Controllers/Web/Admin/FileController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Gambar;
use App\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;
use Illuminate\Support\Str;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $gambar = Gambar::all();
        return view('admin.file.beranda',compact('gambar'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        if ($request->hasFile('file')) {
            $this->deletePhoto('katalog.pdf');
            $this->savePhoto($request->file('file'));
        }

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data File";
        History::create($histori);

        $notification = array(
            'message' => 'Data File berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('file.index')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function savePhoto(UploadedFile $photo)
    {
        $fileName = 'katalog.pdf';
        $destinationPath = 'itlabil/file/';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = 'itlabil/file/' . $filename;
        return File::delete($path);
    }
}

resources/views/admin/file/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

  <section class="content-header">
    <h1>
      File
    </h1>
  </section><br><br>

  <div class="row">

    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ganti File Katalog</h3>
        </div>
        <form action="{{ route('file.store') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="box-body">
            <div class="form-group">
              <label for="photo" class="col-sm-2 control-label">File</label>

              <div class="col-sm-8">
                <input type="file" name="file" id="cat_image">
                <br>
                *File berextensi .pdf
              </div>
            </div>
          </div>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection