routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Web\User\BerandaController@index');
Route::resource('/kontak', 'Web\User\KontakController');
Route::resource('/laporan', 'Web\User\LaporanController');
Route::post('/pesan/store', 'Web\User\BerandaController@store');
Route::get('/gallery', 'Web\User\BerandaController@gallery');
Route::get('/video', 'Web\User\BerandaController@video');
Route::get('download/katalog', 'Web\User\BerandaController@download');
Route::get('/hubungi', 'Web\User\BerandaController@hubungi');

Auth::routes(['register' => false]);

Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/prinsip', 'Web\Admin\PrinsipController');
Route::resource('/admin/gambar', 'Web\Admin\GambarController');
Route::resource('/admin/video', 'Web\Admin\VideoController');
Route::resource('/admin/pesan', 'Web\Admin\PesanController');
Route::resource('/admin/photo', 'Web\Admin\GalleryController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/progres', 'Web\Admin\ProgresController');
Route::resource('/admin/testimoni', 'Web\Admin\TestimoniController');
Route::resource('/admin/pertanyaan', 'Web\Admin\PertanyaanController');
Route::resource('/admin/tim', 'Web\Admin\TimController');
Route::resource('/admin/file', 'Web\Admin\FileController');
Route::get('/admin/cetak/pesan/print/{id}', 'Web\Admin\PesanController@pesan');
Route::get('/admin/cetak/pesan-semua/print', 'Web\Admin\PesanController@pesansemua');

app/Progres.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Progres extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/ProgresController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Gambar;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProgresRequest;
use App\Progres;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;
use Illuminate\Support\Str;

class ProgresController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $gambar = Gambar::all();
        $data = Progres::all();
        return view('admin.progres.beranda', compact('data', 'gambar'));
    }

    public function create()
    {
        //
    }

    public function store(ProgresRequest $request)
    {
        $data = $request->only('judul');

        if ($request->hasFile('photo')) {
            $data['photo'] = $this->savePhoto($request->file('photo'));
        }

        Progres::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Progres " . $request->judul;
        History::create($histori);

        $notification = array(
            'message' => 'Data Progres "' . $request->judul . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('progres.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $progres = Progres::findOrFail($id);
        $gambar = Gambar::all();
        return view('admin.progres.edit', compact('progres', 'gambar'));
    }

    public function update(Request $request, $id)
    {
        $progres = Progres::findOrFail($id);

        $data = $request->only('judul');

        if ($request->hasFile('photo')) {
            $this->deletePhoto($progres->photo);
            $data['photo'] = $this->savePhoto($request->file('photo'));
        }

        $progres->update($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Progres " . $progres->judul;
        History::create($histori);

        $notification = array(
            'message' => 'Data Progres "' . $progres->judul . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('progres.index')->with($notification);
    }

    public function destroy($id)
    {

        $progres = Progres::findOrFail($id);
        $this->deletePhoto($progres->photo);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Progress " . $progres->judul;
        History::create($histori);

        $notification = array(
            'message' => 'Data Progres ' . $progres->judul . ' berhasil dihapus.',
            'alert-type' => 'error'
        );

        $progres->delete();

        return redirect()->route('progres.index')->with($notification);
    }

    protected function savePhoto(UploadedFile $photo)
    {
        $fileName = Str::random(10) . '.' . $photo->guessClientExtension();
        $destinationPath = 'itlabil/images/progres';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = 'itlabil/images/progres/' . $filename;
        return File::delete($path);
    }
}

resources/views/admin/progres/beranda.blade.php
@extends('layouts.admin')

@section('content')


<div class="container">

  <section class="content-header">
    <h1>
      Progres
    </h1>
  </section><br><br>

  <div class="row">

    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data Progres</h3>
        </div>
        <form action="{{ route('progres.store') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="box-body">

            <div class="form-group">
              <label for="judul" class="col-sm-2 control-label">Judul</label>

              <div class="col-sm-10">
                <input type="text" name="judul" class="form-control" placeholder="Judul">
                <small class="text-danger">{{ $errors->first('judul') }}</small>
              </div>
            </div>

            <div class="form-group">
              <label for="photo" class="col-sm-2 control-label">Photo</label>

              <div class="col-sm-8">
                <input type="file" name="photo" id="cat_image">
              </div>
            </div>
          </div>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Gambar Preview</h3>
        </div>
        <div class="box-body">
          <img src="#" id="category-img-tag" class="img-thumbnail" width="300px" />
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Progres</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Judul</th>
                <th>Photo</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>

              @foreach($data as $item)
              <tr>
                <td>{{ $item->judul }}</td>
                <td><img src="{{asset('itlabil/images/progres/'.$item->photo) }}" class="img-thumbnail" width="300px" alt=""></td>
                <td align="center">
                  <form action="{{ route('progres.destroy',$item->id) }}" method="POST">
                    <a href="{{ route('progres.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/progres/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Data Progres
        </h1>
    </section><br><br>

    <div class="row">

        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Data Progres</h3>
                </div>
                <form action="{{ route('progres.update',$progres->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="box-body">
                        <div class="form-group">
                            <label for="judul" class="col-sm-4 control-label">Judul</label>

                            <div class="col-sm-8">
                                <input type="text" value="{{$progres->judul}}" name="judul" class="form-control" placeholder="Judul">
                                <small class="text-danger">{{ $errors->first('judul') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Photo" class="col-sm-4 control-label">Photo</label>

                            <div class="col-sm-8">
                                <input type="file" name="photo" id="cat_image">
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <a href="{{url('admin/progres')}}" class="btn btn-default">Kembali</a>
                        <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Gambar Sebelumnya</h3>
                </div>
                <div class="box-body">
                    <img src="{{asset('itlabil/images/progres/'.$progres->photo) }}" class="img-thumbnail" width="300px" alt="">
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Gambar Preview</h3>
                </div>
                <div class="box-body">
                    <img src="#" id="category-img-tag" class="img-thumbnail" width="300px" />
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection